name: Tox

on:
  push:
    branches:
      - "master"

  pull_request:
    branches:
      - "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tox:
    name: Tox

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          update-environment: true
          cache: pip
          cache-dependency-path: |
            setup.cfg
            tox.ini

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions

      - name: Set up problem matchers
        run: echo "::add-matcher::.github/problem-matchers.json"

      - name: Run tox
        run: tox
